import assert from 'node:assert/strict';
import test from 'node:test';
import { COGNITIVE_STAGES, createCognitiveLearningEngine, startCognitiveSession, advanceCognitiveStage, processCognitiveAttempt, completeCognitiveFeedback, promoteCognitiveMemory, buildCognitivePlan, evaluateCognitiveTransfer, createActiveRecall, createInterleavedSet, createProgressiveSummary, createSelfTest, createSocraticPrompt, createTeachBackActivity, recordMetacognitiveReflection, selectKnowledgeGapAction } from '../src/rechercher-cognitive-learning-engine.js';
import { registerTransferConcept, addTransferEdge } from '../src/rechercher-transfer-graph-engine.js';
import { registerPedagogyPolicy } from '../src/rechercher-pedagogy-safety-engine.js';

test('cognitive loop preserves ordered stages and source links', () => { const engine = createCognitiveLearningEngine(); const session = startCognitiveSession(engine, { sessionId: 's1', learnerId: 'u1', itemId: 'c1', sourceIds: ['src-1'], now: '2026-01-01T00:00:00.000Z' }); assert.deepEqual(COGNITIVE_STAGES, ['UNDERSTAND','PRACTICE','RETRIEVE','FEEDBACK','MASTERY','TRANSFER','REPLAN']); advanceCognitiveStage(engine, session.sessionId, 'RETRIEVE'); assert.equal(session.stage, 'RETRIEVE'); assert.throws(() => advanceCognitiveStage(engine, session.sessionId, 'PRACTICE'), /cannot move backwards/); });
test('attempt creates bounded feedback and auditable session memory', () => { const engine = createCognitiveLearningEngine({ feedback: { maxPending: 2 } }); startCognitiveSession(engine, { sessionId: 's2', learnerId: 'u2', itemId: 'c2', sourceIds: ['src-2'] }); const result = processCognitiveAttempt(engine, 's2', { conceptId: 'c2', promptId: 'p2', answer: 'answer', correct: false, confidence: 0.8 }, { sourceIds: ['src-3'] }); assert.equal(result.feedbackId, 's2:2'); assert.equal(engine.feedback.items.size, 1); assert.equal(engine.memory.sessions.get('s2').events.length, 2); });
test('feedback resolution and long-term memory require explicit inputs', () => { const engine = createCognitiveLearningEngine(); startCognitiveSession(engine, { sessionId: 's3', learnerId: 'u3', itemId: 'c3' }); const { feedbackId } = processCognitiveAttempt(engine, 's3', { conceptId: 'c3', promptId: 'p3', answer: 'x', correct: true }); assert.equal(completeCognitiveFeedback(engine, feedbackId, { outcome: 'CORRECT' }).state, 'RESOLVED'); const memory = promoteCognitiveMemory(engine, { learnerId: 'u3', memoryId: 'm3', key: 'mastery-note', value: { conceptId: 'c3' }, sourceIds: ['src-3'] }); assert.deepEqual(memory.sourceIds, ['src-3']); });
test('cognitive plan blocks missing pedagogy policy and accepts reviewed allowed policy', () => { const engine = createCognitiveLearningEngine(); const blocked = buildCognitivePlan(engine, { learnerId: 'u4', conceptId: 'c4', pedagogyItem: { itemId: 'i4' } }); assert.equal(blocked.safety.decision, 'REVIEW_REQUIRED'); registerPedagogyPolicy(engine.pedagogySafety, { policyId: 'p-safe', name: 'source-first' }); const reviewed = buildCognitivePlan(engine, { learnerId: 'u4', conceptId: 'c4', pedagogyItem: { itemId: 'i4', policyId: 'p-safe', decisionId: 'd4', evidenceState: 'SCHOLAR_REVIEWED', rightsStatus: 'ALLOWED', humanReviewed: true } }); assert.equal(reviewed.safety.decision, 'ALLOW'); });
test('transfer planning only returns evidence above the configured threshold', () => { const engine = createCognitiveLearningEngine(); registerTransferConcept(engine.transferGraph, { conceptId: 'c5', domain: 'hadith', title: 'Concept A' }); registerTransferConcept(engine.transferGraph, { conceptId: 'c6', domain: 'fiqh', title: 'Concept B' }); addTransferEdge(engine.transferGraph, { edgeId: 'e5', fromConceptId: 'c5', toConceptId: 'c6', confidence: 0.8, evidenceSourceIds: ['src-5'] }); const plan = buildCognitivePlan(engine, { learnerId: 'u5', conceptId: 'c5', minTransferConfidence: 0.75 }); assert.equal(plan.transfers[0].conceptId, 'c6'); });
test('transfer evaluation requires novel-context performance and explanation quality', () => { assert.equal(evaluateCognitiveTransfer({ correct: true, novelContext: true, explanationQuality: 0.8 }).transferred, true); assert.equal(evaluateCognitiveTransfer({ correct: true, novelContext: false, explanationQuality: 0.8 }).transferred, false); });
test('v5 learning methods are available', () => { const e = createCognitiveLearningEngine(); createActiveRecall(e, ['c1']); createInterleavedSet(e, ['c1','c2']); createProgressiveSummary(e, 'c1', ['one']); createSelfTest(e, ['c1']); createSocraticPrompt(e, 'c1', 'Question'); createTeachBackActivity(e, 'c1'); recordMetacognitiveReflection(e, { learnerId:'u6', prompt:'Reflection' }); assert.equal(e.activities.length, 6); assert.equal(e.reflections.length, 1); assert.equal(selectKnowledgeGapAction({ lowRetrieval:true }), 'ACTIVE_RECALL'); });
