name: OSV-Scanner

on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
  push:
    branches: [main]
  schedule:
    - cron: "12 12 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    name: OSV vulnerability scan
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@0c58c542420dfd23fcac08dd9c8ca3cca9c36f1a
    with:
      scan-args: |-
        --include-git-root
        -r
        ./
